platform :ios,"7.0"
inhibit_all_warnings!

pod 'AFNetworking'
pod 'SDWebImage'
pod 'SVPullToRefresh'
pod 'JSONKit'
pod 'MBProgressHUD'
pod 'AMScrollingNavbar'
pod 'Masonry'
pod 'HTHorizontalSelectionList'
pod 'MJExtension'
pod 'MJRefresh'
